name: art_portfolio_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.1
  freezed_annotation: ^1.1.0
  font_awesome_flutter: ^9.2.0
  go_router: ^2.5.2
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_flavorizr: ^2.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    dev:
      app:
        name: "dev Art Portfolio"

      android:
        applicationId: "org.gwc.art_portfolio_flutter.dev"

      ios:
        bundleId: "org.gwc.art-portfolio-flutter.dev"

    prod:
      app:
        name: "Art Portfolio"

      android:
        applicationId: "org.gwc.art_portfolio_flutter.prod"
      ios:
        bundleId: "org.gwc.art-portfolio-flutter.prod"
