name: gwc_art_portfolio_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  json_annotation: ^4.3.0
  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_flavorizr: ^2.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    dev:
      app:
        name: "dev Art Portfolio"

      android:
        applicationId: "org.gwc.art_portfolio_flutter.dev"

      ios:
        bundleId: "org.gwc.art-portfolio-flutter.dev"

    prod:
      app:
        name: "Art Portfolio"

      android:
        applicationId: "org.gwc.art_portfolio_flutter.prod"
      ios:
        bundleId: "org.gwc.art-portfolio-flutter.prod"
